using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Robust.Roslyn.Shared;
using Robust.Roslyn.Shared.Helpers;

namespace Robust.Shared.EntitySystemSubscriptionsGenerator;

[Generator(LanguageNames.CSharp)]
public class SubscriptionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var knownTypes = context.CompilationProvider.Select((c, _) => KnownTypesInfo.Get(c));
        var annotatedDeclCandidates = context.SyntaxProvider.ForAttributeWithMetadataName(
            KnownTypesInfo.GenerateEventSubscriptionsAttributeName,
            (ctx, _) => ctx is TypeDeclarationSyntax,
            (ctx, _) => ((INamedTypeSymbol)ctx.TargetSymbol, (TypeDeclarationSyntax)ctx.TargetNode)
        );

        context.RegisterImplementationSourceOutput(
            annotatedDeclCandidates.Combine(knownTypes).Select(ParseAnnotatedDecls),
            AddSource
        );

        ValidateMethodsInCorrectType(context, knownTypes);
    }

    private static WithDiagnostics<AnnotatedTypeDeclInfo> ParseAnnotatedDecls(
        ((INamedTypeSymbol, TypeDeclarationSyntax), KnownTypesInfo) values,
        CancellationToken cancellationToken
    )
    {
        var ((symbol, syntax), types) = values;
        var partialTypeInfo = PartialTypeInfo.FromSymbol(symbol, syntax);

        if (!symbol.AllInterfaces.Contains(types.IEntitySystemSymbol, SymbolEqualityComparer.IncludeNullability))
        {
            return new JustDiagnostics<AnnotatedTypeDeclInfo>(
                Diagnostic.Create(
                    Diagnostics.NotIEntitySystem,
                    partialTypeInfo.SyntaxLocation,
                    KnownTypesInfo.GenerateEventSubscriptionsAttributeName,
                    types.IEntitySystemSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)
                )
            );
        }

        if (!partialTypeInfo.IsValid)
        {
            return new JustDiagnostics<AnnotatedTypeDeclInfo>(
                Diagnostic.Create(
                    Diagnostics.NotPartial,
                    partialTypeInfo.SyntaxLocation,
                    KnownTypesInfo.GenerateEventSubscriptionsAttributeName
                )
            );
        }

        var methods = new List<WithDiagnostics<MethodInfo>>();
        foreach (var method in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            if (method is null ||
                MethodInfo.Parse(method, types) is not { } methodInfo)
                continue;

            methods.Add(methodInfo);
        }

        return methods.Lift(methodInfos =>
            new AnnotatedTypeDeclInfo(
                partialTypeInfo,
                EquatableArray<MethodInfo>.FromImmutableArray([..methodInfos]))
        );
    }

    private static void AddSource(
        SourceProductionContext ctx,
        WithDiagnostics<AnnotatedTypeDeclInfo> typeDeclWd
    )
    {
        typeDeclWd.ReportDiagnostics(ctx);
        if (!typeDeclWd.TryGetValue(out var typeDecl))
            return;

        var subscriptionsSyntax = new StringBuilder();
        var callAfterSyntax = new StringBuilder();
        foreach (var method in typeDecl.Methods)
        {
            if (method is CallAfterMethod callAfter)
            {
                callAfterSyntax.AppendLine($"{callAfter.Method.Name}();");
                continue;
            }

            ctx.CancellationToken.ThrowIfCancellationRequested();
            var syntax = method switch
            {
                ParsedDirectedEventHandler m =>
                    $"SubscribeLocalEvent<{m.ComponentType}, {m.EventType}>({m.Method.Name});",
                ParsedEventHandler m =>
                    $"{GetSubscriptionMethod(m.SubscriptionType)}<{m.EventType}>({m.Method.Name});",
                ParsedSessionEventHandler m =>
                    $"{GetSubscriptionMethod(m.SubscriptionType)}<{m.EventType}>({m.Method.Name});",
                CallAfterMethod => throw new("Unreachable"),
                _ => throw new ArgumentOutOfRangeException(nameof(method))
            };
            subscriptionsSyntax.AppendLine(syntax);
        }

        var builder = new StringBuilder(@"
// <auto-generated />

using Robust.Shared.GameObjects;

");
        typeDecl.PartialTypeInfo.WriteHeader(builder);
        builder.AppendLine($@"
{{
    [MustCallBase]
    public override void Initialize()
    {{
        base.Initialize();

        {subscriptionsSyntax}

        {callAfterSyntax}
    }}
}}
");

        typeDecl.PartialTypeInfo.WriteFooter(builder);

        ctx.AddSource(typeDecl.PartialTypeInfo.GetGeneratedFileName(), builder.ToString());
    }

    private void ValidateMethodsInCorrectType(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<KnownTypesInfo> typesProvider
    )
    {
        Validate(ForAttributeWithMetadataName(KnownTypesInfo.CallAfterSubscriptionsAttributeName));
        Validate(ForAttributeWithMetadataName(KnownTypesInfo.AllSubscriptionMemberAttributeName));
        Validate(ForAttributeWithMetadataName(KnownTypesInfo.LocalSubscriptionMemberAttributeName));
        Validate(
            ForAttributeWithMetadataName(KnownTypesInfo.NetworkSubscriptionMemberAttributeName));
        return;

        IncrementalValuesProvider<IMethodSymbol?> ForAttributeWithMetadataName(string annotationName) =>
            context.SyntaxProvider.ForAttributeWithMetadataName(
                annotationName,
                (ctx, _) => ctx is MethodDeclarationSyntax,
                (ctx, _) => ctx.TargetSymbol as IMethodSymbol
            );

        void Validate(IncrementalValuesProvider<IMethodSymbol?> incrementalValuesProvider)
        {
            context.RegisterSourceOutput(incrementalValuesProvider.Combine(typesProvider),
                (ctx, input) =>
                {
                    var (method, types) = input;
                    if (method is null)
                        return;

                    if (method.ContainingType is not { } containingType ||
                        !AttributeHelper.HasAttribute(
                            containingType,
                            types.GenerateEventSubscriptionsAnnotationSymbol.ToString(),
                            out _
                        ))
                    {
                        ctx.ReportDiagnostic(
                            Diagnostic.Create(
                                Diagnostics.AnnotatedMethodInNotAnnotatedType,
                                method.Locations[0],
                                types.IEntitySystemSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                                types.GenerateEventSubscriptionsAnnotationSymbol.ToDisplayString(SymbolDisplayFormat
                                    .CSharpErrorMessageFormat)
                            )
                        );
                    }
                });
        }
    }

    private static string GetSubscriptionMethod(SubscriptionType type) => type switch
    {
        SubscriptionType.All => "SubscribeAllEvent",
        SubscriptionType.Network => "SubscribeNetworkEvent",
        SubscriptionType.Local => "SubscribeLocalEvent",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
    };

    private sealed record AnnotatedTypeDeclInfo(PartialTypeInfo PartialTypeInfo, EquatableArray<MethodInfo> Methods);
}
